spring.application.name=DentalAI
amazon.dynamodb.endpoint=https://dynamodb.${AWS_REGION}.amazonaws.com
amazon.aws.accesskey=${AWS_ACCESS_KEY_ID}
amazon.aws.secretkey=${AWS_SECRET_ACCESS_KEY}
spring.datasource.url=jdbc:mysql://localhost:3306/dentalai
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.jpa.hibernate.ddl-auto=update
